config/routes.rb
Rails.application.routes.draw do
  root 'classrooms#index'
  resources :classrooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  validates_presence_of :name, :teacher
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1
  def show
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  def create
    @classroom = Classroom.new(classroom_params)

    if @classroom.save
      redirect_to @classroom, notice: 'Classroom was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /classrooms/1
  def update
    if @classroom.update(classroom_params)
      redirect_to @classroom, notice: 'Classroom was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /classrooms/1
  def destroy
    @classroom.destroy
    redirect_to classrooms_url, notice: 'Classroom was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def classroom_params
      params.require(:classroom).permit(:name, :code, :teacher, :student_count, :active, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_form.html.erb
<%= form_with(model: classroom, local: true) do |form| %>
  <% if classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :classroom_name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :classroom_code %>
  </div>

  <div class="field">
    <%= form.label :teacher %>
    <%= form.text_field :teacher, id: :classroom_teacher %>
  </div>

  <div class="field">
    <%= form.label :student_count %>
    <%= form.number_field :student_count, id: :classroom_student_count %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :classroom_active %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :classroom_category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<h1>Editing Classroom</h1>

<%= render 'form', classroom: @classroom %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>

app/views/classrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Classrooms</h1>

<% if @classrooms.any? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Code</th>
        <th>Teacher</th>
        <th>Student count</th>
        <th>Active</th>
        <th>Category</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @classrooms.each do |classroom| %>
        <tr>
          <td><%= classroom.name %></td>
          <td><%= classroom.code %></td>
          <td><%= classroom.teacher %></td>
          <td><%= classroom.student_count %></td>
          <td><%= classroom.active %></td>
          <td><%= classroom.category %></td>
          <td><%= link_to 'Show', classroom %></td>
          <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
          <td><%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3>No Classrooms, Please Create One!</h3>
<% end %>

<br>

<%= link_to 'New Classroom', new_classroom_path %>

app/views/classrooms/new.html.erb
<h1>New Classroom</h1>

<%= render 'form', classroom: @classroom %>

<%= link_to 'Back', classrooms_path %>

app/views/classrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @classroom.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @classroom.code %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @classroom.teacher %>
</p>

<p>
  <strong>Student count:</strong>
  <%= @classroom.student_count %>
</p>

<p>
  <strong>Active:</strong>
  <%= @classroom.active %>
</p>

<p>
  <strong>Category:</strong>
  <%= @classroom.category %>
</p>

<%= link_to 'Edit', edit_classroom_path(@classroom) %> |
<%= link_to 'Back', classrooms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningSelenium</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>